# SPDX-FileCopyrightText: 2019-2024 MartinTheDragon <martin@ntmr.dev>
# SPDX-License-Identifier: GPL-3.0-or-later

modLoader="javafml"
loaderVersion="[47,)"
license="GPL v3.0"
issueTrackerURL="https://codeberg.org/MartinTheDragon/Nuclear-Tech-Mod-Remake/issues"
[[mods]]
modId="nucleartech"
version="${file.jarVersion}"
displayName="Nuclear Tech Mod"
displayURL="https://codeberg.org/MartinTheDragon/Nuclear-Tech-Mod-Remake"
updateJSONURL="https://www.ntmr.dev/.well-known/ntmr/update.json"
credits="HbM: Did well..."
authors="MartinTheDragon"
description='''All the high quality nuclear bombs and machinery you can only find in this mod or in the older 1.7.10 version!
The mod with both quantity and quality ;D
A recreation by MartinTheDragon of HbMinecraft's Nuclear Tech Mod.
'''
[[dependencies.nucleartech]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"
[[dependencies.nucleartech]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"
[[dependencies.nucleartech]]
modId="jei"
mandatory=false
versionRange="[15.0.0,)"
ordering="NONE"
side="BOTH"
